### PR TITLE
June 2021 - Test/fix

### PR DESCRIPTION
**Pull request by JulienAlbo**
Please review. Sorry I did create issue myself. Closing #39 

I did follow the instructions and run through the complete lab. I can now complete all steps with success.
Almost all Azure images were updated, respecting guidelines and using Snag It.

Small technical fixes were applied:

- Microsoft Data Migration Assistant requires framework .Net 4.8! Both are not installed at custom deployment level with ARM template. I did add steps to manually install both .Net 4.8 and Migration Assistant.
- WideWorldImporters Database is not deployed with ARM template, manual installation was already describe, I simply added a note at the end of _Before the HOL_, to check and install it before walking through the lab. 

Instructions were slightly updated.

- There were confusion around checking MI requirements, and validating ARM json file. I simply did split task 3 of _Before the HOL_: one task to validate, on task to deploy. Confusion is mostly based on ARM deploy process update in Azure. But since deployment last 4 hours, mistakes could be annoying when preparing lab requirements.

Only suggestions issued by markdown linters were applied to whiteboard design session. Content is perfect on that side.

### CODE REVIEW

**Review by saimachi — COMMENTED** [review]
Hello @JulienAlbo,

Your updates make the lab easier to follow, and I didn't encounter any major problems. However, I would recommend that you add the following:

1. In the Manual Resource Deployment document, change the date to June 2021.
2. In Exercise 1, Task 3, Step 10, there is an image that renders strangely, with the text wrapping improperly.
3. In Exercise 2, Task 3, Step 1, the image does not render. Please update the file path.
4. There is an incomplete sentence in Exercise 1, Task 2, Step 4, in the "Install Framework 4.8" section.

Other than these minor issues, everything in the Azure UI appeared updated.

@timahenning: I forwarded you some additional thoughts, regarding future content updates.

**Comment by JulienAlbo** [comment]
Thanks for that review. I'll check that right away and will commit soon I guess.

**Comment by JulienAlbo** [comment]
Commit changes to take review's notes into consideration.

**Comment by saimachi** [comment]
Thank you, @JulienAlbo, I believe that your changes are ready for merging.

**Comment by JulienAlbo** [comment]
You're welcome @saimachi, that's nice of you to review my first MCW PR with patience!

**Pull request merged**
